server {
    listen 80;
    index index.php index.html;
    server_name localhost; # Cambia esto por tu dominio si es necesario
    disable_symlinks off;
    root /var/www/html/public;
    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    location ~* \.(jpg|jpeg|png|gif|svg|webp)$ {
        expires 30d;
        access_log off;
    }
}